# Site settings
baseURL = "http://samrainhan.com/"
languageCode = "zh-cn"
title = "sam的小窝"
author = "Sam Han"
theme = "ink"
canonifyurls = true
paginate = 5
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = true

[params]
	author = "韩雨"
	description = "学习 & 生活"
	bio = "学习 & 生活"
	# Enter optionally your twitter account
	twitter = "samrain"
	facebook = "samrain"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "samrainblogbygithub"



	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = false
	googleAnalytics = "UA-37708730-1"

	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	baiduAnalytics = ''

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""

	olderPosts = ""
	newerPosts = ""
	copyright = "韩雨"

	# show latest posts in single page
	showLatestPosts = true
	readMore = ""

	mode = "auto"

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "font-awesome"

  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 15 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/samrain" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/samrain"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/samrainhan/"
  [[params.social]]
    name = "email"
    link = "samrainhan@gmail.com"  # no need for "mailto:" in the head

# Add additional social link entries underneath
[social]
	facebook-square = ""
	twitter-square = ""
	github-square = "https://github.com/samrain"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"
archive = "archives"

[permalinks]
  post = "/:year/:month/:title/"
  
# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
