blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/z8wNYzb
    about: Chat live with the Wowchemy community on Discord.
  - name: Discussions
    url: https://github.com/HugoBlox/hugo-blox-builder/discussions
    about: Discuss Wowchemy on the GitHub Discussions forum
  - name: Troubleshooting Guide
    url: https://hugoblox.com/docs/hugo-tutorials/troubleshooting/
    about: Solve common issues fast.
  - name: Documentation
    url: https://hugoblox.com/docs/
    about: Review the documentation
