[build]
  command = "hugo -c ./exampleSite/content/ --config ./exampleSite/config.toml --baseURL https://hugo-theme-inkblotty.netlify.com -t ''"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.59.1"
  HUGO_ENABLEGITINFO = "false"
