title = "TeXify3"
description = "TeXify3 - A LaTeX-style hugo theme with the gruvbox color scheme for personal blogging"
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
keywords = ["hugo", "latex", "theme", "blog", "texify", "texify2", "texify3", "michael", "neuper"]
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
since = "2023"
toc = true
showWordCount = true
showReadingTime = true
rootFontSize = "100%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true
enableInlineShortcodes = true

[commentEngine]
code = """
<script src="https://giscus.app/client.js"
    data-repo="michaelneuper/hugo-texify3"
    data-repo-id="R_kgDOIjPNaQ"
    data-category="General"
    data-category-id="DIC_kwDOIjPNac4CaklA"
    data-mapping="pathname"
    data-strict="0"
    data-reactions-enabled="1"
    data-emit-metadata="0"
    data-input-position="top"
    data-theme=""
    data-lang="en"
    data-loading="lazy"
    crossorigin="anonymous"
    async>
</script>
"""

[buymeacoffee]
code = """
<script data-name="BMC-Widget" 
    data-cfasync="true" 
    src="https://cdnjs.buymeacoffee.com/1.0.0/widget.prod.min.js" 
    data-id="michaelneuper" 
    data-description="Like what I do? Buy me a coffee!" 
    data-message="" 
    data-color="#d79921" 
    data-position="Right" 
    data-x_margin="18" 
    data-y_margin="18"
    crossorigin="anonymous">
</script>
"""

[sharingbuttons]
facebook = true
twitter = true
email = true
linkedin = true
reddit = true
whatsapp = true
hackernews = true
telegram = true
