name = "henry"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"

summary = "Henry is a gorgeous Hugo theme optimmized for a good reading experience and packed with features"
homepage = "https://kau.sh/blog/henry-hugo-theme/"

tags = ["blog", "minimal", "responsive", "archive", "personal", "bootstrap", "portfolio", "dark"]
features = ["clean reading experience", "beautiful font & type", "customizable & versatile", "footnotes", "sidenotes", "multiple image display combinations", "image attribution captions", "external url", "daring fireball style urls", "canonical urls", "alternate urls aliases", "rss feed clean", "seo optimized"]

[author]
  name = "Kaushik Gopal"
  homepage = "https://kau.sh"