module:
  mounts:
    - source: data
      target: data
    - source: functions
      target: layouts/partials/mod-decap-cms
    - source: templates
      target: layouts/decap_cms
outputFormats:
  decap_cms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false
mediaTypes:
  application/yaml:
    suffixes:
      - yml
